### PR TITLE
Make `Monitor` optional

### LINKED ISSUE #166: pin the gym version in the requirements.txt, latest gym breaks pfrl
Getting an error, probably due to versioning issue between pfrl 0.2.1 and gym 0.23.0:

d:\python-x64\lib\site-packages\pfrl\wrappers\monitor.py line 4: ImportError: cannot import name 'Monitor' from 'gym.wrappers' (D:\python-x64\lib\site-packages\gym\wrappers\__init__.py)

```
python -m pip list
Package                              Version   Location
------------------------------------ --------- -----------------------
gym                                  0.23.0
pfrl                                 0.2.1
```

Downgrading gym fixes it:
```
python -m pip uninstall gym
python -m pip install gym==0.14.0
```

Could you pin the gym version in the requirements.txt?

### PR DESCRIPTION
**Pull request by toslunar**
Fix #166.

### CODE REVIEW

File: .pfnci/run.sh [hunk 1]
```diff
@@ -72,10 +72,9 @@ main() {
 
   "${PYTHON}" -m pip install /pfrl
   # TODO(pfrl): Prepare test target instead.
-  # pytest does not run with attrs==19.2.0 (https://github.com/pytest-dev/pytest/issues/3280)  # NOQA
   "${PYTHON}" -m pip install \
-      'pytest==4.1.1' 'attrs==19.1.0' 'pytest-xdist==1.26.1' \
-      'gym[atari,classic_control]==0.19.0' 'optuna' 'zipp==1.0.0' 'pybullet==2.8.1' 'jupyterlab==2.1.5'
+      'pytest==7.0.1' 'pytest-xdist==2.5.0' \
+      'gym[atari,classic_control]==0.19.0' 'optuna' 'zipp==1.0.0' 'pybullet==2.8.1' 'jupyterlab==3.3.1'
```
Comment (muupan) [inline .pfnci/run.sh:77]: What issue do these version changes try to solve? I confirmed that at least for the jupyter-related issue in pfn.cpu.examples CI can be resolved by #169 .

Comment (toslunar) [reply .pfnci/run.sh:77]: Thanks. I tried to fix the jupyter issue. I'll revert the change to this file.

File: pfrl/wrappers/monitor.py [hunk 2]
```diff
@@ -1,8 +1,22 @@
...
+            raise RuntimeError("Monitor is not available in this version of gym")
+
+    class _GymMonitor(_Stub):  # type: ignore
+        pass
+
+    class _GymStatsRecorder(_Stub):
+        pass
+
+else:
+    from gym.wrappers.monitoring.stats_recorder import StatsRecorder as _GymStatsRecorder  # type: ignore, isort: skip
```
Comment (muupan) [inline pfrl/wrappers/monitor.py:19]:
```suggestion
    from gym.wrappers.monitoring.stats_recorder import StatsRecorder as _GymStatsRecorder  # type: ignore, isort: skip  # noqa: E501
```

to suprress the flake8 error https://ci.preferred.jp/pfrl.lint/96643/#L51

**Comment by muupan** [comment]
I confirmed that this PR works as follows.
Before this PR, `gym==0.23.0` causes an error when `import pfrl`:
```
python examples/gym/train_dqn_gym.py --gpu -1 --env Pendulum-v1
Traceback (most recent call last):
  File "examples/gym/train_dqn_gym.py", line 23, in <module>
    import pfrl
  File "/Users/user/pfndev/pfrl/pfrl/__init__.py", line 20, in <module>
    from pfrl import wrappers  # NOQA
  File "/Users/user/pfndev/pfrl/pfrl/wrappers/__init__.py", line 4, in <module>
    from pfrl.wrappers.monitor import Monitor  # NOQA
  File "/Users/user/pfndev/pfrl/pfrl/wrappers/monitor.py", line 4, in <module>
    from gym.wrappers import Monitor as _GymMonitor
ImportError: cannot import name 'Monitor' from 'gym.wrappers' (/Users/user/.local/share/virtualenvs/pfrl-1dLBIXZi/lib/python3.7/site-packages/gym/wrappers/__init__.py)
```

After this PR, `import pfrl` works fine with `gym==0.23.0`. An error is raised only when I try to use Monitor.
```
python examples/gym/train_dqn_gym.py --gpu -1 --env Pendulum-v1
Output files are saved in results/466f63ad18ea725928ebf7ad22d929ec9c453dad-70cd82e5-3ec14d5f
WARNING: Since https://github.com/pfnet/pfrl/pull/112 we have started setting `eval_during_episode=True` in this script, which affects the timings of evaluation phases.
INFO:pfrl.experiments.train_agent:outdir:results/466f63ad18ea725928ebf7ad22d929ec9c453dad-70cd82e5-3ec14d5f step:200 episode:0 R:-1.157075492297421
INFO:pfrl.experiments.train_agent:statistics:[('average_q', nan), ('average_loss', nan), ('cumulative_steps', 200), ('n_updates', 0), ('rlen', 200)]
INFO:pfrl.experiments.train_agent:outdir:results/466f63ad18ea725928ebf7ad22d929ec9c453dad-70cd82e5-3ec14d5f step:400 episode:1 R:-1.397539478750692
INFO:pfrl.experiments.train_agent:statistics:[('average_q', nan), ('average_loss', nan), ('cumulative_steps', 400), ('n_updates', 0), ('rlen', 400)]
INFO:pfrl.experiments.train_agent:outdir:results/466f63ad18ea725928ebf7ad22d929ec9c453dad-70cd82e5-3ec14d5f step:600 episode:2 R:-1.6421154508871758
INFO:pfrl.experiments.train_agent:statistics:[('average_q', nan), ('average_loss', nan), ('cumulative_steps', 600), ('n_updates', 0), ('rlen', 600)]
INFO:pfrl.experiments.train_agent:outdir:results/466f63ad18ea725928ebf7ad22d929ec9c453dad-70cd82e5-3ec14d5f step:800 episode:3 R:-1.5671076399681863
...
```
```
python examples/gym/train_dqn_gym.py --gpu -1 --monitor --env Pendulum-v1
Output files are saved in results/466f63ad18ea725928ebf7ad22d929ec9c453dad-70cd82e5-17449428
Traceback (most recent call last):
  File "examples/gym/train_dqn_gym.py", line 272, in <module>
    main()
  File "examples/gym/train_dqn_gym.py", line 122, in main
    env = make_env(test=False)
  File "examples/gym/train_dqn_gym.py", line 111, in make_env
    env = pfrl.wrappers.Monitor(env, args.outdir)
  File "/Users/user/pfndev/pfrl/pfrl/wrappers/monitor.py", line 10, in __init__
    raise RuntimeError("Monitor is not available in this version of gym")
```
With `gym==0.22.0`, `--monitor` won't raise any error.

**Review by muupan — APPROVED** [review]

File: pfrl/wrappers/monitor.py [hunk 3]
```diff
@@ -1,8 +1,22 @@
...
+            raise RuntimeError("Monitor is not available in this version of gym")
+
+    class _GymMonitor(_Stub):  # type: ignore
+        pass
+
+    class _GymStatsRecorder(_Stub):
+        pass
+
+else:
+    from gym.wrappers.monitoring.stats_recorder import StatsRecorder as _GymStatsRecorder  # type: ignore, isort: skip  # noqa: E501
```
Comment (muupan) [inline pfrl/wrappers/monitor.py:19]: Sorry, I haven't checked mypy for the previous suggestion, but `# type: ignore, isort: skip` seems not working for mypy, causing another error in CI. https://ci.preferred.jp/pfrl.lint/96657/#L52
```suggestion
    from gym.wrappers.monitoring.stats_recorder import StatsRecorder as _GymStatsRecorder  # type: ignore  # isort: skip  # noqa: E501
```
I confirmed this now pass black, isort, flake8, and mypy.
